myapp/urls.py
from django.urls import path
from . import views

from django.views.generic import TemplateView
from .views import ContactFormView, ContactResultView

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('program/<int:pk>/', views.post_detail, name='post_detail'),
    path('program/new/', views.post_new, name='post_new'),
    path('program/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
    path('program/<pk>/publish/', views.post_publish, name='post_publish'),
    path('program/<pk>/remove/', views.post_remove, name='post_remove'),
    path('program/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('comment/list/', views.comment_list, name='comment_list'),
    path("vietnam_research/post_okini/<int:user_id>/<int:program_id>",views.post_okini,name="post_okini"),
    path("vietnam_research/like_com/<int:user_id>/<int:comment_id>",views.like_com,name="like_com"),
    path('program/search/', views.post_search, name='post_search'),
    path('program/search/genre', views.genre_search, name='genre_search'),
    path('program/search/dj', views.dj_search, name='dj_search'),

    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_confirm', TemplateView.as_view(template_name='registration/delete_confirm.html'), name='delete-confirmation'),
    path('delete_complete', views.DeleteView.as_view(), name='delete-complete'),
    # 運営からのお知らせ
    path('info/', views.info_list, name='info_list'),
    # ユーザーページ
    path('user/<int:pk>/', views.user_detail, name='user_detail'),
    path('user/<int:pk>/edit/', views.user_edit, name='user_edit'),

    # お問い合わせ
    path('contact/', ContactFormView.as_view(), name='contact_form'),
    path('contact/result/', ContactResultView.as_view(), name='contact_result'),

    # 意見箱
    path('opinion/', views.opinion_form, name='opinion_form'),

    # ページ情報
    path('pageinfo/', views.pageinfo, name='pageinfo'),

    # 利用規約
    path('terms/', views.terms, name='terms'),

    # プライバシーポリシー
    path('privacy/', views.privacy, name='privacy'),
]

radiosite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views
# ログイン・サインアップ
from myapp import views as viewss

from myapp.views import Top

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),  # 1. 元々提供されている機能へ振り分け
    path('', include('myapp.urls')),
    # ログイン・サインアップ
    path('create_account', viewss.SignUpView.as_view(), name='create_account') ,
    # path('accounts/', include('myapp.urls')), # 2. 自作の機能へ振り分け
]

myapp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

# ログイン・サインアップ
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.contrib.auth.validators import UnicodeUsernameValidator

class Program(models.Model):

    title = models.CharField(
        verbose_name='番組名',
        max_length=200
    )

    corner_title = models.CharField(
        verbose_name='コーナー名',
        max_length=200,
        blank=True,
        null=True,
    )

    address = models.EmailField(
        verbose_name='メールアドレス',
        blank=True,
        null=True,
    )

    url = models.URLField(
        verbose_name='公式Webページ',
        blank=True,
        null=True,
    )

    genrelist = models.ManyToManyField(
        'myapp.Genre',
        verbose_name='ジャンル',
        blank=True,
        related_name='genres',
    )

    created_date = models.DateTimeField(
        verbose_name='作成時間',
        blank=True,
        null=True,
        default=timezone.now,
    )

    published_date = models.DateTimeField(
        verbose_name='更新時間',
        blank=True,
        null=True,
        default=timezone.now,
    )
    
    okini_num = models.IntegerField(
      verbose_name='お気に入り',
      default=0
    )

    

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def station_names(self):
        return self.stations.all()

    def dj_names(self):
        return self.djs.all()

    def listener_name(self):
        return self.listener_names.all()

    def okini_program(self):
        return self.okini_program

# 各ラジオ局のオンエア時間
class Station(models.Model):

    program = models.ForeignKey(
      'myapp.Program',
      on_delete=models.CASCADE,
      related_name='stations',
    )

    station_choice = (
        (0, '指定なし'),
        (1, 'TBSラジオ'),
        (2, 'ニッポン放送'),
        (3, '文化放送'),
        (4, 'NHK'),
    )

    station_name = models.IntegerField(
        verbose_name='ラジオ局',
        choices=station_choice,
    )

    day_of_the_week = models.ManyToManyField(
        'myapp.Week',
        verbose_name='曜日',
        blank=True,
        related_name='day_of_the_weeks',
    )

    start_time = models.TimeField (
        verbose_name='開始時間',
        blank=True,
        null=True,
    )

    end_time = models.TimeField (
        verbose_name='終了時間',
        blank=True,
        null=True,
    )


# 曜日
class Week(models.Model):

    week_choice = (
        (1, '月'),
        (2, '火'),
        (3, '水'),
        (4, '木'),
        (5, '金'),
        (6, '土'),
        (7, '日'),
    )

    weeks = models.IntegerField(
        verbose_name='曜日',
        choices=week_choice,
        null=True,
        unique=True,
    )

    def __str__(self):
        return self.get_weeks_display()


# 出演者
class Dj(models.Model):

    program = models.ForeignKey(
      'myapp.Program',
      on_delete=models.CASCADE,
      related_name='djs',
    )

    dj_name = models.CharField(
        verbose_name='出演者',
        max_length=100
    )

    main_dj = models.BooleanField(
        verbose_name='メインパーソナリティ',
    )

    def __str__(self):
        return self.dj_name


# はがき職人
class Listener(models.Model):

    program = models.ForeignKey(
      'myapp.Program',
      on_delete=models.CASCADE,
      related_name='listeners',
    )

    listener_name = models.CharField(
        verbose_name='主なハガキ職人',
        max_length=100
    )

    def __str__(self):
        return self.listener_name

# ジャンル
class Genre(models.Model):

    genre_choice = (
        ('var', 'バラエティ'),
        ('mus', '音楽'),
        ('news', 'ニュース'),
        ('edu', '教育'),
        ('info', '情報'),
        ('hob', '趣味'),
    )

    genre_name = models.CharField(
        verbose_name='ジャンル',
        choices=genre_choice,
        null=True,
        unique=True,
        max_length=4,
    )

    def __str__(self):
        return self.get_genre_name_display()

# お気に入り
class Okini(models.Model):

    user = models.ForeignKey(
      settings.AUTH_USER_MODEL,
      on_delete=models.CASCADE,
      related_name='okini_user',
    )

    program = models.ForeignKey(
      Program,
      on_delete=models.CASCADE,
      related_name='okini_program',
    )

    date_created = models.DateTimeField(
      auto_now_add=True
    )

    def __str__(self):
        return self.program

# コメント
class Comment(models.Model):

    program = models.ForeignKey(
      'myapp.Program', 
      on_delete=models.CASCADE, 
      related_name='comments'
    )

    user = models.ForeignKey(
      settings.AUTH_USER_MODEL,
      on_delete=models.CASCADE,
      related_name='comment_user',
    )

    text = models.TextField()
    created_date = models.DateTimeField(
      default=timezone.now
    )
    # 承認されたコメント
    approved_comment = models.BooleanField(
      default=False
    )

    like_user = models.ManyToManyField(
      settings.AUTH_USER_MODEL,
      blank=True,
      related_name="like_users"
    )

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def like_comment(self):
        return self.like_comment

# 運営からのお知らせ
class Info(models.Model):

    title = models.CharField(
        verbose_name='題名',
        max_length=200
    )

    text = models.TextField(
        verbose_name='お知らせ内容',
        blank=True,
        null=True,
    )
    created_date = models.DateTimeField(
      default=timezone.now
    )

class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    username_validator = UnicodeUsernameValidator()
    username = models.CharField(
        _('username'),
        max_length=150,
        # unique=True,
        help_text=_('この項目は必須です!半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。'),
        validators=[username_validator],
        # error_messages={
        #     'unique': _("A user with that username already exists."),
        # },
    )
    profile = models.TextField(
        verbose_name='紹介文',
        blank=True,
        null=True,
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    # USERNAME_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


# 意見箱
class Opinion(models.Model):

    name = models.CharField(
        verbose_name='名前',
        max_length=200
    )

    text = models.TextField(
        verbose_name='ご意見',
        blank=True,
        null=True,
    )
    created_date = models.DateTimeField(
      default=timezone.now
    )

myapp/forms.py
from django import forms
from .models import *
# ログイン・サインアップ
from django.forms import EmailField

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

# お問い合わせ
from django.conf import settings
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse

class PostForm(forms.ModelForm):

    class Meta:
        model = Program
        fields = ('title', 'url', 'address', 'corner_title','genrelist',)

    # チェックボックスに切替
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            self.fields['genrelist'].widget = forms.CheckboxSelectMultiple(attrs={'class': 'control'}) 
            self.fields['genrelist'].queryset = Genre.objects

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)


class StationForm(forms.ModelForm):

    class Meta:
        model = Station
        fields = '__all__'

    # チェックボックスに切替
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            self.fields['day_of_the_week'].widget = forms.CheckboxSelectMultiple(attrs={'class': 'control'}) 
            self.fields['day_of_the_week'].queryset = Week.objects



class WeekForm(forms.ModelForm):

    class Meta:
        model = Week
        fields = ('weeks',)


class DjForm(forms.ModelForm):

    class Meta:
        model = Dj
        fields = ('dj_name', 'main_dj',)

class GenreForm(forms.ModelForm):

    class Meta:
        model = Genre
        fields = ('genre_name',)

class ListenerForm(forms.ModelForm):

    class Meta:
        model = Listener
        fields = ('listener_name',)

class OkiniForm(forms.ModelForm):

    class Meta:
        model = Okini
        fields = ('user','program')

StationFormset = forms.inlineformset_factory(
    # 親親モデル
    parent_model = Program,
    # 子モデル
    model = Station,
    form = StationForm,
    fields='__all__',
    extra=1, can_delete=False
)

DjFormset = forms.inlineformset_factory(
    Program, Dj,  fields='__all__',
    extra=5, can_delete=False
)

ListenerFormset = forms.inlineformset_factory(
    Program, Listener,  fields='__all__',
    extra=3, can_delete=False
)

# ログイン・サインアップ
# class SignUpForm(UserCreationForm):

#     class Meta:
#         model = User
#         fields = ('email', 'username', 'password1', 'password2')

#     def save(self, commit=True):
#         user = super(SignUpForm, self).save(commit=False)
#         user.email = self.cleaned_data['email']
#         if commit:
#             user.save()
#         return user


User = get_user_model()


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email','username',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('email','username','profile')

# お問い合わせ
class ContactForm(forms.Form):
    name = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': "お名前",
        }),
    )
    email = forms.EmailField(
        label='',
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': "メールアドレス",
        }),
    )
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': "お問い合わせ内容",
        }),
    )

    def send_email(self):
        subject = "お問い合わせ"
        message = self.cleaned_data['message']
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        from_email = '{name} <{email}>'.format(name=name, email=email)
        recipient_list = [settings.EMAIL_HOST_USER]  # 受信者リスト
        try:
            send_mail(subject, message, from_email, recipient_list)
        except BadHeaderError:
            return HttpResponse("無効なヘッダが検出されました。")

# 意見箱
class OpinionForm(forms.ModelForm):

    class Meta:
        model = Opinion
        fields = ('name','text')

myapp/templates/myapp/base.html
{% load static %}
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Django Girls blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
        <!-- likes -->
        <script src="{% static 'vietnam_research/js/ajax.js' %}" charset="utf-8"></script>
        <script src="https://cdn.jsdelivr.net/npm/js-cookie@beta/dist/js.cookie.min.js"></script>    

    </head>
    <body>
      <div class="page-header">
        {% if user.is_authenticated %}
          <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
          <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
          <p class="top-menu">Hello <a href="{% url 'user_detail' pk=user.pk %}">{{ user.username }}</a><small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
        {% else %}
          <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
        {% endif %}
          <h1><a href="/">ラジコネ！</a></h1>

      </div>
      <div class="content container">
          <div class="row">
              <div class="col-md-8">
              {% block content %}
              {% endblock %}
              </div>
          </div>
      </div>
  </body>

</html>

myapp/templates/myapp/comment_list.html
{% extends 'myapp/base.html' %}

{% block content %}

    <h1>コメント一覧</h1>
    {% for comment in comments %}
        {% if comment.approved_comment %}
            <div class="comment">
                <strong>
                  <a href="{% url 'user_detail' pk=comment.user.pk %}">
                    {{ comment.user.username }}
                  </a>
                </strong>
                <div class="date">
                  {{ comment.created_date }}
                </div>
                <strong>
                  <a href="{% url 'post_detail' pk=comment.program.pk %}">
                    {{ comment.program }}
                  </a>
                </strong>
                <p>{{ comment.text }}</p>

                <!-- いいね -->
                {% if user.is_authenticated %}
                    {% if user in comment.like_user.all %}
                        <a class="btn btn-default" aria-pressed="true" onclick="like_com(event, '{{ user.id }}', '{{ comment.id }}')">
                        いいね<span>({{ comment.like_user.count }})</span></a>
                    {% else %}
                        <a class="btn btn-default" aria-pressed="false" onclick="like_com(event, '{{ user.id }}', '{{ comment.id }}')">
                        いいね<span>({{ comment.like_user.count }})</span></a>
                    {% endif %}
                {% else %}
                    お気に入り<span>({{ comment.like_user.count }})</span>
                {% endif %}
            </div>
        {% endif %}
    {% empty %}
        <p>No comments here </p>
    {% endfor %}
{% endblock %}

myapp/templates/myapp/contact_result.html
{% extends 'myapp/base.html' %}

{% block content %}
{{ success }}
<h1>送信完了</h1>
<a href="/">
<p>トップへ</p>
{% endblock %}

myapp/templates/myapp/post_detail.html
{% extends 'myapp/base.html' %}

{% block content %}
    <div class="post">

        {% if user.is_authenticated %}
          <a class="btn btn-default" href="{% url 'post_edit' pk=program.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        {% endif %}
        <h2>{{ program.title }}</h2>
        <p>出演者：
          {% for dj in program.djs.all %}
            {{ dj.dj_name }}
            {% if not forloop.last %}
              ,
            {% endif %}
          {% endfor %}
        </p>
        <p>公式Webページ：<a href="">{{ program.url }}</a></p>
        <p>コーナー：{{ program.corner_title|linebreaksbr }}</p>
        <p>
          {% for station in program.stations.all %}

            {{ station.get_station_name_display }}：

            <!-- 曜日の表示 -->
            {% for day_of_the_week in station.day_of_the_week.all %}
              {{ day_of_the_week }}
            {% endfor%}

            {{ station.start_time }} 〜 {{ station.end_time }}
            {% if not forloop.last %}
              <br>
            {% endif %}
          {% empty %}
            No select 
          {% endfor %}
        </p>
        <p>ジャンル：
          {% for genre in program.genrelist.all %}
            {{ genre }}
          {% endfor%}
        </p>

        <p>主なはがき職人：
          {% for listener in program.listeners.all %}
            {{ listener.listener_name }}
            {% if not forloop.last %}
              ,
            {% endif %}
          {% endfor %}
        </p>

        <!-- okini -->
            <div class="article">
              {% if user.is_authenticated %}
                <ul>
                    {% if okini_sign > 0 %}
                        <a class="btn btn-default" aria-pressed="true" onclick="post_okini(event, '{{ user.id }}', '{{ program.id }}')">
                    {% else %}
                        <a class="btn btn-default" aria-pressed="false" onclick="post_okini(event, '{{ user.id }}', '{{ program.id }}')">
                    {% endif %}
                    お気に入り<span>({{ program.okini_program.count }})</span></a>
                </ul>
                {% else %}
                <ul>
                    お気に入り<span>({{ program.okini_program.count }})</span>
                </ul>
              {% endif %}
            </div>

    </div>

    <hr>
    {% if user.is_authenticated %}
        <a class="btn btn-default" href="{% url 'add_comment_to_post' pk=program.pk %}">Add comment</a>
    {% endif %}
    {% for comment in program.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
            <div class="comment">
                <div class="date">
                  {{ comment.created_date }}
                  {% if not comment.approved_comment %}
                      <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                      <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                  {% endif %}
                </div>
                <strong>
                  <a href="{% url 'user_detail' pk=comment.user.pk %}">
                    {{ comment.user.username }}
                  </a>
                </strong>
                <p>{{ comment.text|linebreaks }}</p>
            </div>
        {% endif %}
    {% empty %}
        <p>No comments here </p>
    {% endfor %}

{% endblock %}

myapp/templates/myapp/post_list.html
{% extends 'myapp/base.html' %}

{% block content %}
  <form method="GET" action="{% url 'post_search' %}">
    <legend>検索</legend>
    <input type="text" name="keyword">
    <button type="submit">検索</button>
  </form>

  <form method="GET" action="{% url 'genre_search' %}" name="filter_form">
    <legend>絞り込み条件</legend>
    <div>
        <span>ジャンル：</span>
        {% for genre in genres %}
            <input type="checkbox" id="filter_kind_{{ genre.pk }}" 
                name="genre" 
                value="{{ genre.pk }}">{{ genre.get_genre_name_display }}
        {% endfor %}
        <button id="filter">絞り込み</button>
    </div>
  </form>

  <form method="GET" action="{% url 'dj_search' %}" name="filter_form">
    <legend>絞り込み条件</legend>
    <div>
        <span>パーソナリティ</span>
        {% for dj in djs %}
            <input type="checkbox" id="filter_kind_{{ dj.pk }}" 
                name="dj" 
                value="{{ dj.pk }}">{{ dj.dj_name }}
        {% endfor %}
        <button id="filter">絞り込み</button>
    </div>
  </form>

  {% for food in object_list %}
  <tr>
      <td>{{ food.get_genre_name_display }}</td>
      <td>{{ food.title }}</td>
  </tr>
  {% endfor %} 

    <h1>ONAIR番組（TBS）</h1>

    {% for program in onair_programs_TBS %}
        <div class="post">
          <h2>
            <a href="{% url 'post_detail' pk=program.pk %}">
              {{ program.program.title }}
            </a>
          </h2>
          <p>出演者：
          {% for dj in program.program.djs.all %}
            {{ dj.dj_name }}
            <!-- 末尾ではない場合 -->
            {% if not forloop.last %}
              ,
            {% endif %}
          {% endfor %}
          </p>
          {% for day_of_the_week in program.day_of_the_week.all %}
            {{ day_of_the_week }}
          {% endfor%}
          {{ program.start_time }} 〜 {{ program.end_time }}
          <p>お気に入り：{{ program.program.okini_num }}</p>

          <a href="{% url 'post_detail' pk=program.pk %}">

            Comments: {{ program.program.okini_num }}
          </a>
      </div>
    {% endfor %}
    <h1>新着コメント</h1>
    {% for new_coment in new_coments %}

        {% if new_coment.approved_comment %}
            <div class="comment">
                <strong>
                  <a href="{% url 'user_detail' pk=new_coment.user.pk %}">
                    {{ new_coment.user.username }}
                  </a>
                </strong>
                <div class="date">
                  {{ new_coment.created_date }}
                </div>
                <strong>
                  <a href="{% url 'post_detail' pk=new_coment.program.pk %}">
                    {{ new_coment.program }}
                  </a>
                </strong>
                <p>{{ new_coment.text|linebreaks|truncatechars:100 }}</p>

                <!-- いいね -->
                {% if user.is_authenticated %}
                    {% if user in new_coment.like_user.all %}
                        <a class="btn btn-default" aria-pressed="true" onclick="like_com(event, '{{ user.id }}', '{{ new_coment.id }}')">
                        いいね<span>({{ new_coment.like_user.count }})</span></a>
                    {% else %}
                        <a class="btn btn-default" aria-pressed="false" onclick="like_com(event, '{{ user.id }}', '{{ new_coment.id }}')">
                        いいね<span>({{ new_coment.like_user.count }})</span></a>
                    {% endif %}
                {% else %}
                    お気に入り<span>({{ new_coment.like_user.count }})</span>
                {% endif %}
            </div>
        {% endif %}
    {% empty %}
        <p>No comments here </p>
    {% endfor %}
    <a class ="btn btn-default" href="{% url 'comment_list' %}">もっと見る</a>
    <h1>ジャンル別TOP５</h1>

    {% for key, value in programs.items %}
        <h2>{{ key }}</h2>
        {% for program in value %}
            <div class="post">
                <h2>
                  <a href="{% url 'post_detail' pk=program.pk %}">
                    {{ program.title }}
                  </a>
                </h2>
                <p>出演者：
                {% for dj in program.djs.all %}
                  {{ dj.dj_name }}
                  {% if not forloop.last %}
                    ,
                  {% endif %}
                {% endfor %}
                </p>
                <p>ラジオ局：
                {% for station in program.stations.all %}
                  {{ station.get_station_name_display }}
                  {% if not forloop.last %}
                    /
                  {% endif %}
                {% empty %}
                  No select 
                {% endfor %}
                </p>
                <p>お気に入り：{{ program.okini_num }}</p>
                <a href="{% url 'post_detail' pk=program.pk %}">
                  Comments: {{ program.okini_num }}
                </a>
            </div>
        {% endfor %}
    {% endfor %}
    <h1>運営からのお知らせ</h1>
    {% for info in infos %}
        <h2>
            {{ info.title }}
        </h2>
        <div class="date">
          {{ info.created_date }}
        </div>
        <p>
            {{ info.text|linebreaks }}
        </p>
    {% endfor %}
    <a class ="btn btn-default" href="{% url 'info_list' %}">
      もっと見る
    </a>
    <div>
      <a href="{% url 'pageinfo' %}">ラジコネ！とは</a>
    </div>
    <div>
        <a href="{% url 'contact_form' %}">お問い合わせ</a>
    </div>
    <div>
      <a href="{% url 'opinion_form' %}">意見箱</a>
    </div>
    <div>
      <a href="{% url 'terms' %}">利用規約</a>
    </div>
    <div>
      <a href="{% url 'privacy' %}">プライバシーポリシー</a>
    </div>
{% endblock %}